### ISSUE TITLE
Add support for multiple cameras

### ISSUE THREAD

**Issue by modiius** [modiius/rtspmetrics#2]
- [ ] Add a config that allows multiple RTSP sessions
```yaml
rtsp:
  sessions:
    # Example:
    # - name: "Camera 1"
    #   url: "rtsp://camera1.example.com/stream"
    - name: "Camera 2"
      url: "rtsp://camera2.example.com/stream"
```
- [ ] Spawn a goroutine per RTSP session 💡 
- [ ] Emit metrics per RTSP session (with fields name and RTSP URL)
